POST http://localhost:3001/api/account/signup
content-Type: application/json

{
    "name": "Joe",
    "email": "johndoe@example.com",
    "phone": "9898989898",
    "password": "password123"
}

# Expected response
# HTTP/1.1 200 OK
# Content-Type: application/json

# {
#     "message": "Signup successful!",
#     "token": "<JWT token>"
# }

###

POST http://localhost:3001/api/account/login
content-Type: application/json

{
    "email": "newmail@iiitd.ac.in",
    "password": "password123"
}

# Expected response
# HTTP/1.1 200 OK
# Content-Type: application/json

# {
#     "message": "Login successful!",
#     "token": "<JWT token>"
# }
