POST http://localhost:3001/appointments/6172ca031dab0d2fd420cd13
Content-Type: application/json

{
  "clinic_id": "6172c9e01dab0d2fd420cd0f",
  "date_time": "2023-05-01T10:00:00Z",
  "doctor_name": "Dr. Smith"
}

# Update an appointment
PATCH http://localhost:3001/appointments/6173f3ca04d0dc5d5c6c5f6f
Content-Type: application/json

{
  "clinic_id": "6172c9e01dab0d2fd420cd0f",
  "doctor_name": "Dr. Lee",
  "completed": true
}

# Delete an appointment
DELETE http://localhost:3001/appointments/6173f3ca04d0dc5d5c6c5f6f
