POST http://localhost:3001/api/appointments/
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0M2VlYWExODU0OTFmMTlmYTZkNTRmIiwiaWF0IjoxNjgyMjA0MjMzLCJleHAiOjE2ODIyNDAyMzN9._t0IJt1D5_YkVzY7bKn9qzcWghnO3AP2hedLnJOs35E
Content-Type: application/json

{
  "petId": "64441dfa9ef3ea504adbfdb6",
  "clinic_id": "6443ef20e88b1e28738d0e47",
  "date_time": "2023-05-01T10:00:00Z",
  "doctor_name": "Dr. Smith"
}

###
# Update an appointment
PATCH http://localhost:3001/api/appointments/6444325dde1c01a2838fa8bf
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0M2VlYWExODU0OTFmMTlmYTZkNTRmIiwiaWF0IjoxNjgyMjA0MjMzLCJleHAiOjE2ODIyNDAyMzN9._t0IJt1D5_YkVzY7bKn9qzcWghnO3AP2hedLnJOs35E
Content-Type: application/json

{
  "petId": "64441dfa9ef3ea504adbfdb6",
  "doctor_name": "Dr. Lee",
  "completed": true
}

###
# Delete an appointment
DELETE http://localhost:3001/api/appointments/6444325ede1c01a2838fa8c5
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0M2VlYWExODU0OTFmMTlmYTZkNTRmIiwiaWF0IjoxNjgyMjA0MjMzLCJleHAiOjE2ODIyNDAyMzN9._t0IJt1D5_YkVzY7bKn9qzcWghnO3AP2hedLnJOs35E
Content-Type: application/json

{
  "petId": "64441dfa9ef3ea504adbfdb6"
}