GET http://localhost:3001/api/articles
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0M2VlYWExODU0OTFmMTlmYTZkNTRmIiwiaWF0IjoxNjgyMTg4NTM0LCJleHAiOjE2ODIxOTIxMzR9.wZ112K5KnaaJkjjDBSujLEHmPJLunySNqtK7EV1PDko

###
POST http://localhost:3001/api/articles/64442228609a706a155dd0b6
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0M2VlYWExODU0OTFmMTlmYTZkNTRmIiwiaWF0IjoxNjgyMTg4NTM0LCJleHAiOjE2ODIxOTIxMzR9.wZ112K5KnaaJkjjDBSujLEHmPJLunySNqtK7EV1PDko

###
DELETE http://localhost:3001/api/articles/64442228609a706a155dd0b6
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0M2VlYWExODU0OTFmMTlmYTZkNTRmIiwiaWF0IjoxNjgyMTg4NTM0LCJleHAiOjE2ODIxOTIxMzR9.wZ112K5KnaaJkjjDBSujLEHmPJLunySNqtK7EV1PDko
