GET http://localhost:3001/api/clinics
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0M2VlYWExODU0OTFmMTlmYTZkNTRmIiwiaWF0IjoxNjgyMTczNjExLCJleHAiOjE2ODIxNzcyMTF9.kDa8C3CnWQlrJwll4HZvUZGdZgo1CfWs1kTSiTOypOw

###
POST http://localhost:3001/api/clinics/6443ef20e88b1e28738d0e47/reviews
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0M2VlYWExODU0OTFmMTlmYTZkNTRmIiwiaWF0IjoxNjgyMTczNjExLCJleHAiOjE2ODIxNzcyMTF9.kDa8C3CnWQlrJwll4HZvUZGdZgo1CfWs1kTSiTOypOw
Content-Type: application/json

{
	"review": "I highly recommend Dr. Sandeep for your pet babies/adult pets as well, he is lovely with pets and looks out for them in every situation.",
	"rating": 5
}