GET http://localhost:3001/api/clinics
authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQ0MWU5MTFlOTNkMDk1MTgzMDliMzU5IiwiaWF0IjoxNjgyMDQxMTEwLCJleHAiOjE2ODIwNDQ3MTB9.9pFc2t_uwJTXqSwjnyCt5oA5xRDXutxcOUKsQfCnN9w

###